# Anonymous Ratings from the Jester Online Joke Recommender System

# Abstract:

Ratings are real values ranging from -10.00 to +10.00 (the value "99" corresponds to "null" = "not rated").

One row per user

The first column gives the number of jokes rated by that user. The next 100 columns give the ratings for jokes 01 - 100.

# Dataset:
    
http://eigentaste.berkeley.edu/dataset/

The text of the jokes can be downloaded here: jester_dataset_1_joke_texts.zip (92KB)

Read the dataset(jokes.csv)

Take care about the header in read_csv() as there are no column names given in the dataset.

In [27]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.set_option('display.max_colwidth', -1)

In [28]:
data = pd.read_csv('jokes.csv')

In [29]:
data.head()

74  -7.82   8.79  -9.66  -8.16  -7.52  -8.5  -9.85  4.17  -8.98  -4.76  \
0  100  4.08  -0.29   6.36   4.37  -2.38  -9.66 -0.73  -5.34  8.88   9.22    
1  49   99.00  99.00  99.00  99.00  9.03   9.27  9.03   9.27  99.00  99.00   
2  48   99.00  8.35   99.00  99.00  1.80   8.16 -2.82   6.21  99.00  1.84    
3  91   8.50   4.61  -4.17  -5.39   1.36   1.60  7.04   4.61 -0.44   5.73    
4  100 -6.17  -3.54   0.44  -8.50  -7.09  -4.32 -8.69  -0.87 -6.65  -1.80    

   -8.5.1  -6.75  -7.18  8.45  -7.18.1  -7.52.1  -7.43  -9.81  -9.85.1  \
0  6.75    8.64   4.42   7.43  4.56    -0.97     4.66  -0.68   3.30      
1  7.33    7.57   9.37   6.17 -6.36    -6.89    -7.86   9.03   9.03      
2  7.33    6.60   6.31   8.11 -7.23    -6.65     1.17  -6.60  -3.64      
3  8.25    6.84  -3.93   7.23 -2.33    -9.66     2.72  -1.36   2.57      
4 -6.80   -5.73  -5.00  -8.59  0.49    -8.93    -3.69  -2.18  -2.28      

   -9.85.2  -9.37    1.5  -4.37  -9.81.1  -8.5.2  1.12  7.82  2.86  9.13  \
0 -1.21     0.87   8.64   8.35   9.17     0.05    7.57  4.71  0.87 -0.39   
1  9.03     7.28   99.00  8.25   99.00    99.00   7.48  7.28  7.28  8.93   
2 -2.09     5.34   99.00  99.00  99.00    99.00   2.91  3.93  6.75  6.60   
3  4.51     8.20   6.12   8.30  -1.26     7.77    1.89 -1.17  5.68  8.45   
4 -6.12    -3.01  -0.58  -2.38  -7.77    -2.23   -2.28 -5.24 -5.53 -0.68   

   -7.43.1  2.14  -4.08  -9.08  7.82.1  5.05  4.95  -9.17  -8.4  -8.4.1  \
0  6.99     6.50 -0.92   7.14   9.03   -1.80  0.73  7.09   3.40 -0.87     
1  99.00    6.17  7.28   99.00  99.00   8.98  7.33  99.00  6.17  9.08     
2  99.00    6.65 -6.12   99.00  7.57    6.21  6.65  99.00 -8.30  7.18     
3  4.61     8.06 -9.47   7.28   5.68    2.48  3.20 -1.26   6.80  4.51     
4 -6.94    -3.93 -0.34  -6.60  -5.49   -1.55 -0.49 -6.21  -8.06 -5.39     

   -8.4.2  -8.11  -9.13  -9.03  -9.08.1  -7.14  -6.26  3.79  -0.1  3.93  4.13  \
0  7.91    7.82  -3.83   8.64   8.98    -4.32  -3.20  -4.90 -0.92 -1.46  3.64   
1  7.33    7.52   9.27   9.27   99.00    9.27   99.00  6.17  7.33  9.08  7.28   
2  2.82    99.00  1.55   99.00  99.00    99.00  6.84   6.84 -3.98  6.99  3.45   
3  2.48    0.34   6.84   0.19  -8.74     5.24   6.31   8.06  1.26  4.51 -0.05   
4 -7.04   -8.83  -7.91   1.07  -1.89    -6.36  -4.22  -9.27 -9.81 -7.82 -0.63   

   -8.69  -7.14.1   3.2   8.3  -4.56  0.92  -9.13.1  -9.42   2.82  -8.64  \
0  3.16   9.03     0.97 -1.31 -6.50  -3.20  8.64    -2.14   0.10   9.03    
1  99.00  99.00    7.28  7.33  99.00  7.23  99.00    99.00  99.00  9.27    
2  99.00  6.94     1.55  7.67  99.00  6.55  99.00    99.00  99.00  99.00   
3  4.42   3.06     8.93  7.82  1.75   8.11 -8.06    -9.17   4.95   3.35    
4 -6.31  -7.48    -6.07 -3.45 -3.20   0.53 -9.27    -9.56  -5.49  -1.12    

   8.59  3.59  -6.84  -9.03.1  2.82.1  -1.36  -9.08.2  8.3.1  5.68  -4.81  \
0 -6.70 -3.35 -9.03   4.47     4.08   -3.83   8.74     1.12   0.78  7.52    
1  6.46  7.28  99.00  99.00    7.04    7.28   99.00    7.28   8.25  99.00   
2  0.00 -3.69  99.00  99.00    7.82    0.24   99.00    7.28  -2.33  99.00   
3  7.38  6.17  4.71  -2.28     7.38    4.56   7.14     4.22   3.01  3.83    
4 -6.65 -2.86 -4.61  -9.42    -7.91   -9.81  -9.42    -8.98  -1.94 -6.99    

      99   99.1  99.2   99.3   99.4   99.5   99.6  -9.42.1   99.7   99.8  \
0 -5.00   2.77   8.3   7.77   7.33   6.21   7.72   8.98     8.64   8.20    
1  99.00  99.00  99.0  99.00  99.00  8.93   99.00  99.00    99.00  9.08    
2  99.00  99.00  99.0  99.00  99.00  99.00  99.00  99.00    99.00  99.00   
3  99.00  99.00  99.0  99.00  99.00  99.00  4.13   99.00    99.00  99.00   
4 -9.66  -5.19  -5.0  -4.42  -7.28  -6.50  -4.32  -6.94    -9.85   0.73    

    99.9  -7.72  99.10  99.11  99.12  99.13  99.14  99.15  99.16  99.17  \
0  3.93   4.85   4.85   6.07   8.98   4.51  -0.05   3.69   4.56   0.58    
1  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  9.03    
2  99.00  99.00  99.00  99.00  0.63   99.00  99.00 -2.33   99.00  99.00   
3  5.24   5.92   0

Consider ratings named dataframe with only first 200 rows and all columns from 1(first column is 0) of dataset

In [30]:
ratings = data.iloc[:200,1:]

Change the column indices from 0 to 99

In [31]:
ratings.columns = range(ratings.shape[1])

In the dataset, the null ratings are given as 99.00, so replace all 99.00s with 0

Hint: You can use ratings.replace(<the given value>, <new value you wanted to change with>)

In [32]:
ratings = ratings.replace(99.0, 0)

In [33]:
ratings

0     1     2     3     4     5     6     7     8     9    10    11  \
0    4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  6.75  8.64   
1    0.00  0.00  0.00  0.00  9.03  9.27  9.03  9.27  0.00  0.00  7.33  7.57   
2    0.00  8.35  0.00  0.00  1.80  8.16 -2.82  6.21  0.00  1.84  7.33  6.60   
3    8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  8.25  6.84   
4   -6.17 -3.54  0.44 -8.50 -7.09 -4.32 -8.69 -0.87 -6.65 -1.80 -6.80 -5.73   
5    0.00  0.00  0.00  0.00  8.59 -9.85  7.72  8.79  0.00  0.00  4.27  7.62   
6    6.84  3.16  9.17 -6.21 -8.16 -1.70  9.27  1.41 -5.19 -4.42  8.20 -7.86   
7   -3.79 -3.54 -9.42 -6.89 -8.74 -0.29 -5.29 -8.93 -7.86 -1.60 -2.91 -0.29   
8    3.01  5.15  5.15  3.01  6.41  5.15  8.93  2.52  3.01  8.16  5.53  6.02   
9   -2.91  4.08  0.00  0.00 -5.73  0.00  2.48 -5.29  0.00  1.46  0.00  0.00   
10   1.31  1.80  2.57 -2.38  0.73  0.73 -0.97  5.00 -7.23 -1.36  3.83  1.75   
11   0.00  0.00  0.00  0.00  5.87  0.00  5.58  0.53  0.00  7.14  7.04  0.00   
12   9.22  9.27  9.22  8.30  7.43  0.44  3.50  8.16  5.97  8.98  3.74  5.87   
13   8.79 -5.78  6.02  3.69  7.77 -5.83  8.69  8.59 -5.92  7.52 -4.85 -7.28   
14  -3.50  1.55  2.33 -4.13  4.22 -2.28 -2.96 -0.49  2.91  1.99 -1.99  5.53   
15   0.00 -9.27  0.00  0.00 -7.38  0.00  8.74 -6.31  0.00  2.33  0.00  1.75   
16   3.16  7.62  3.79  8.25  4.22  7.62  2.43  0.97  0.53  0.83  3.50  3.30   
17   4.22  3.64  0.00  0.00  2.52  0.00  4.13 -5.19  0.00  7.91  0.00  2.09   
18   0.00  7.62  0.00  0.00 -8.64  2.43  8.93 -6.60  0.00 -9.47 -2.77 -0.73   
19   2.57 -0.73  0.00  0.00  2.57  0.00 -4.22  2.67  0.00 -1.31  0.73  0.00   
20   7.28  5.39  0.00  0.00 -4.22  0.00  8.93  3.50  0.00  6.12  0.87  0.00   
21   2.72  4.17  6.50 -3.54 -3.30  2.86  7.04  4.95  6.17  8.93  8.88  7.09   
22   2.09 -7.57  4.17 -8.40 -6.31  5.34 -5.19 -5.05 -8.20  2.28  1.17  5.73   
23  -3.93 -1.17  2.28 -0.44 -2.28  2.38 -3.93  4.51 -0.34  7.77 -2.48  0.24   
24   0.00  5.49  3.45  0.00  0.15  4.76  0.10  4.13  8.01  4.76  7.33  8.06   
25   0.00  5.83  0.00  0.00  5.34  0.00 -4.47  2.18 -3.98 -3.25 -3.40  3.45   
26   0.49  0.15  0.15 -9.56 -9.76 -9.61  0.29  1.65 -4.61 -4.71 -5.78  0.73   
27   0.00  0.00  0.00  0.00 -1.70  0.00  8.83 -1.89  0.00  0.00 -5.39  4.76   
28   0.00  4.08  0.00  0.00  5.87  0.00  0.44  2.28  0.00  0.00  0.00  0.00   
29   1.94  0.87  1.41  2.96  4.85  3.01  3.83 -4.27 -0.19  2.52 -3.40 -0.49   
30   0.00  5.68  5.68  0.00  3.45  0.00  4.81 -4.27  0.00  0.00  0.00 -0.29   
31   1.02  3.20  3.20  2.86  2.38  1.21  0.97  3.20 -1.41  1.21  3.20  1.12   
32   0.00  0.00  0.00  0.00 -1.99  0.00 -0.19 -4.17  0.00  0.00  0.00  0.00   
33   5.92 -1.65  5.92  5.87  3.06  3.35  2.72  0.10  5.92  2.96  6.31  6.99   
34  -9.66 -8.35  0.00  0.00  0.29  0.00 -9.22 -9.51  0.00  0.00  0.00  0.00   
35   7.18  9.17  9.13  3.74  8.69  7.57 -6.12  6.12  5.15  1.65  2.52  8.74   
36  -3.69 -1.12  0.00  0.00  0.87  0.00  2.18 -2.91  0.00 -2.48  2.82  0.00   
37   2.96  2.96  2.96  2.96  3.74  2.96  3.74  0.78  2.96  2.96  3.20  3.20   
38   0.00  0.00  0.00  0.00 -3.01  0.00 -3.35 -2.28  0.00  0.00  0.00  2.96   
39  -4.95 -2.86  2.23 -6.65  5.44  0.97 -0.97 -5.97 -8.74 -3.45  2.52 -2.48   
40   0.00  0.00  0.00  0.00  8.25  0.00  2.72  0.53  0.00  0.00 -2.96 -7.14   
41   0.00  8.30  0.00  0.00  6.36  0.00 -4.51  3.59  0.00  0.63  6.65  0.00   
42   0.15 -3.20  6.46  2.62 -2.91 -4.37  2.04  2.38 -5.05 -3.01  8.93  1.60   
43   8.79  5.10  5.49  0.92  5.83  7.91  4.51  5.05  7.86  7.04  7.09  7.04   
44   7.33  8.35  5.83 -5.58  5.24 -5.97 -8.16  9.08  6.31  2.43  7.09  7.91   
45   8.45  3.35  7.77  2.77  1.80  8.88  8.59 -9.85 -8.45  3.98  8.50  8.06   
46  -8.25 -1.17  5.10 -0.44  3.79  5.68 -0.53 -8.30 -7.86 -7.91 -1.60  0.63   
47  -5.44  0.68  1.50  3.35 -8.25  3.93  3.30 -1.46  1.46  1.84  3.40  3.20   
48  -7.82  9.17 -9.08 -9.03 -8.93  6.50  7.77 -9.08 -9.42 -7.96 -5.68  4.22   
49   3.16  5.00 -1.31  2.33 -7.33  6.80 -4.13  6.26  5.15 

In [34]:
ratings.describe().T

count     mean       std   min     25%    50%     75%   max
0   200.0  0.56915  4.468725 -9.71 -0.6050  0.000  3.4125  9.27
1   200.0  0.54995  4.880829 -9.95 -2.5950  0.000  4.4425  9.27
2   200.0  0.28595  4.415613 -9.71 -0.6300  0.000  2.3300  9.27
3   200.0 -0.63105  3.854770 -9.76 -1.5250  0.000  0.0000  8.83
4   200.0  0.03515  5.430979 -9.81 -4.1825  0.460  4.2950  9.22
5   200.0  1.36885  4.337548 -9.85  0.0000  0.000  4.9375  9.27
6   200.0  0.26005  5.608396 -9.95 -4.3200  0.970  4.7725  9.27
7   200.0 -0.06175  4.893670 -9.85 -4.2700  0.680  3.4250  9.27
8   200.0  0.08125  3.996228 -9.85 -0.4025  0.000  1.4225  9.03
9   200.0  0.93330  4.991966 -9.76 -1.6375  0.780  4.3200  9.32
10  200.0  1.16725  4.679077 -9.37 -1.1675  0.170  4.6575  9.22
11  200.0  1.38105  4.429679 -9.81 -0.4900  0.340  4.8500  9.22
12  200.0 -1.26995  5.339652 -9.85 -6.2225 -0.680  2.9725  9.37
13  200.0  1.94545  4.468651 -9.56  0.0000  1.915  5.2025  9.27
14  200.0 -1.54600  5.170216 -9.95 -6.2100 -1.145  2.5200  9.22
15  200.0 -2.77735  5.099604 -9.90 -7.1025 -3.035  0.4000  8.98
16  200.0 -0.75365  4.465925 -9.85 -3.7400 -0.580  2.2300  9.13
17  200.0 -0.71520  4.890906 -9.90 -4.3675 -0.190  3.2125  9.03
18  200.0  0.35470  4.741414 -9.42 -3.2750  0.755  3.7525  9.22
19  200.0 -0.78385  5.029678 -9.95 -4.4325 -0.630  3.1100  9.03
20  200.0  2.64830  4.815827 -9.66 -0.3900  3.590  6.7125  9.22
21  200.0  0.97130  4.830010 -9.90 -1.4100  0.000  4.6225  9.32
22  200.0  0.41230  4.749644 -9.95 -1.9025  0.000  3.5000  9.27
23  200.0 -1.02890  4.218262 -9.66 -3.4225  0.000  0.0000  9.17
24  200.0  0.65310  4.542793 -9.71 -2.2300  0.630  3.7900  9.32
25  200.0  1.19685  4.949322 -9.95 -2.2800  0.970  5.1900  9.37
26  200.0  3.05555  4.485145 -9.90  0.1425  4.130  6.6625  9.13
27  200.0  1.09420  4.962639 -9.95 -1.7500  1.120  4.8075  9.17
28  200.0  3.17610  4.907718 -9.56  0.4775  4.150  7.0400  9.32
29  200.0 -0.69145  4.314318 -9.95 -3.5225  0.000  1.2100  9.22
30  200.0  2.64590  4.869406 -9.90 -0.3150  3.200  6.3725  9.32
31  200.0  2.80115  4.735963 -9.47 -0.0250  3.715  6.3950  9.27
32  200.0 -0.00980  4.543962 -9.90 -1.6375  0.000  2.9850  9.37
33  200.0  1.16860  4.663164 -9.56 -1.6250  0.850  4.7725  9.37
34  200.0  3.23745  4.582877 -9.81  0.5450  4.220  6.7850  9.27
35  200.0  3.62390  4.111068 -9.42  1.1575  4.220  6.8900  9.37
36  200.0 -0.62060  4.476009 -9.95 -2.9725  0.000  1.0950  9.13
37  200.0  0.87545  4.928267 -9.90 -1.8400  1.020  3.9925  9.17
38  200.0  1.05000  4.556103 -9.66 -1.6975  0.415  4.6725  9.37
39  200.0  0.71085  4.464234 -9.85 -1.2725  0.000  3.9425  9.17
40  200.0 -0.09060  4.683489 -9.66 -1.9775  0.000  2.7325  9.37
41  200.0  2.20145  4.740482 -9.61 -0.0125  2.790  5.8275  9.27
42  200.0 -0.43675  4.429383 -9.85 -2.6950  0.000  1.8350  9.27
43  200.0 -1.26715  4.273166 -9.95 -4.5225  0.000  0.0000  9.17
44  200.0  0.50790  4.820962 -9.85 -2.6800  0.100  3.6775  9.27
45  200.0  1.83445  4.920628 -9.81 -1.0325  2.795  5.6925  9.32
46  200.0  1.43435  4.745622 -9.95 -0.5000  0.995  5.0750  9.32
47  200.0  1.39040  5.025496 -9.81 -1.5125  2.160  5.1725  9.37
48  200.0  2.86990  4.407001 -9.56 -0.1500  2.985  6.5500  9.32
49  200.0  4.07045  3.924074 -9.81  1.8900  4.760  7.0525  9.37
50  200.0 -0.18425  4.577908 -9.42 -3.1325  0.000  2.9225  9.37
51  200.0  0.63405  4.647167 -9.85 -0.9450  0.000  3.2625  9.27
52  200.0  3.55500  4.483638 -9.47  0.6675  4.270  7.1625  9.37
53  200.0  1.77585  5.175449 -9.61 -1.6250  2.500  6.1200  9.22
54  200.0  1.06880  4.377327 -9.81 -0.5125  0.025  3.8125  9.32
55  200.0  2.39835  4.759664 -9.66 -0.3275  3.085  6.5125  9.32
56  200.0 -0.94615  4.633141 -9.81 -3.8925  0.000  0.0375  9.22
57  200.0 -2.30040  4.126718 -9.85 -6.5375  0.000  0.0000  6.36
58  200.0  0.02065  4.396701 -9.81 -2.8425  0.000  3.0725  9.27
59  200.0 -0.11005  4.885615 -9.90 -2.4050  0.000  2.8850  9.32
60  200.0  2.19915  4.663502 -9.66 -0.3150  2.645  5.6925  9.22
61  200.0  2.79780  4.824398 -9.81 -

Normalize the ratings using StandardScaler and save them in ratings_diff variable

In [35]:
from sklearn.preprocessing import StandardScaler
ratings_diff = StandardScaler().fit_transform(ratings)

In [36]:
ratings_diff

array([[ 0.78762067, -0.17252351,  1.37903679, ...,  0.07059963,
        -1.36765027,  0.16746078],
       [-0.12768256, -0.11295828, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388],
       [-0.12768256,  1.60210964, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388],
       ...,
       [-0.12768256, -0.11295828, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388],
       [ 1.1241292 , -1.60825102, -1.1002121 , ..., -0.02685824,
        -0.04144395, -0.16095388],
       [-0.12768256, -0.11295828, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388]])

# Popularity based recommendation system

Find the mean for each column in ratings_diff i.e, for each joke

In [37]:
mean_ratings = ratings_diff.mean(axis=0)

# Consider all the mean ratings and find the jokes with highest mean value and display the top 10 joke IDs.

In [38]:
mean_ratings = pd.DataFrame(mean_ratings)

In [39]:
mean_ratings.head()

0
0 -3.330669e-17
1 -4.440892e-18
2  1.776357e-17
3  1.554312e-17
4  8.881784e-18

In [41]:
mean_ratings.shape

(100, 1)

In [46]:
mean_ratings.iloc[:,0].argsort()

0     61
1     12
2     60
3     47
4     65
5     57
6     91
7     26
8     84
9     78
10    8 
11    55
12    64
13    89
14    72
15    30
16    56
17    37
18    0 
19    13
20    39
21    9 
22    67
23    93
24    79
25    31
26    43
27    50
28    45
29    98
30    27
31    24
32    92
33    11
34    51
35    86
36    33
37    62
38    66
39    96
40    10
41    87
42    74
43    52
44    18
45    94
46    95
47    40
48    85
49    1 
50    28
51    17
52    58
53    36
54    97
55    82
56    75
57    46
58    42
59    35
60    71
61    7 
62    4 
63    70
64    44
65    59
66    81
67    6 
68    3 
69    90
70    99
71    63
72    2 
73    34
74    32
75    22
76    16
77    5 
78    29
79    53
80    20
81    21
82    25
83    54
84    76
85    14
86    19
87    68
88    69
89    83
90    77
91    73
92    15
93    88
94    38
95    80
96    41
97    23
98    48
99    49
Name: 0, dtype: int64

In [47]:
mean_ratings.iloc[:,0].argsort()[:-10:-1]

99    49
98    48
97    23
96    41
95    80
94    38
93    88
92    15
91    73
Name: 0, dtype: int64

# Content based Recommendation

# Context:

This dataset contains ratings for ten thousand popular books. As to the source, let's say that these ratings were found on the 
internet. Generally, there are 100 reviews for each book, although some have less - fewer - ratings. Ratings go from one to five

Both book IDs and user IDs are contiguous. For books, they are 1-10000, for users, 1-53424. All users have made at least two 
ratings. Median number of ratings per user is 8.

There are also books marked to read by the users, book metadata (author, year, etc.) and tags.

Here is to recommend good book

# Content:

books.csv has metadata for each book (goodreads IDs, authors, title, average rating, etc.).

Book metadata.

best_book_id is the most popular edition for a given work. Generally it's the same as goodreads_book_id, differs occasionally.

books_count is the number of editions for a given work.

# Dataset:
    
https://www.kaggle.com/zygmunt/goodbooks-10k#books.csv

In [48]:
import pandas as pd

df = pd.read_csv('books.csv')

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
id                           10000 non-null int64
book_id                      10000 non-null int64
best_book_id                 10000 non-null int64
work_id                      10000 non-null int64
books_count                  10000 non-null int64
isbn                         9300 non-null object
isbn13                       9415 non-null float64
authors                      10000 non-null object
original_publication_year    9979 non-null float64
original_title               9415 non-null object
title                        10000 non-null object
language_code                8916 non-null object
average_rating               10000 non-null float64
ratings_count                10000 non-null int64
work_ratings_count           10000 non-null int64
work_text_reviews_count      10000 non-null int64
ratings_1                    10000 non-null int64
ratings_2                    10000 n

In [50]:
df.shape

(10000, 23)

In [7]:
df.head()

id  book_id  best_book_id  work_id  books_count       isbn        isbn13  \
0  1   2767052  2767052       2792775  272          439023483  9.780000e+12   
1  2   3        3             4640799  491          439554934  9.780000e+12   
2  3   41865    41865         3212258  226          316015849  9.780000e+12   
3  4   2657     2657          3275794  487          61120081   9.780000e+12   
4  5   4671     4671          245494   1356         743273567  9.780000e+12   

                       authors  original_publication_year  \
0  Suzanne Collins              2008.0                      
1  J.K. Rowling, Mary GrandPré  1997.0                      
2  Stephenie Meyer              2005.0                      
3  Harper Lee                   1960.0                      
4  F. Scott Fitzgerald          1925.0                      

                             original_title  \
0  The Hunger Games                           
1  Harry Potter and the Philosopher's Stone   
2  Twilight                                   
3  To Kill a Mockingbird                      
4  The Great Gatsby                           

                                                      title language_code  \
0  The Hunger Games (The Hunger Games, #1)                   eng            
1  Harry Potter and the Sorcerer's Stone (Harry Potter, #1)  eng            
2  Twilight (Twilight, #1)                                   en-US          
3  To Kill a Mockingbird                                     eng            
4  The Great Gatsby                                          eng            

   average_rating  ratings_count  work_ratings_count  work_text_reviews_count  \
0  4.34            4780653        4942365             155254                    
1  4.44            4602479        4800065             75867                     
2  3.57            3866839        3916824             95009                     
3  4.25            3198671        3340896             72586                     
4  3.89            2683664        2773745             51992                     

   ratings_1  ratings_2  ratings_3  ratings_4  ratings_5  \
0  66715      127936     560092     1481305    2706317     
1  75504      101676     455024     1156318    3011543     
2  456191     436802     793319     875073     1355439     
3  60427      117415     446835     1001952    1714267     
4  86236      197621     606158     936012     947718      

                                                    image_url  \
0  https://images.gr-assets.com/books/1447303603m/2767052.jpg   
1  https://images.gr-assets.com/books/1474154022m/3.jpg         
2  https://images.gr-assets.com/books/1361039443m/41865.jpg     
3  https://images.gr-assets.com/books/1361975680m/2657.jpg      
4  https://images.gr-assets.com/books/1490528560m/4671.jpg      

                                              small_image_url  
0  https://images.gr-assets.com/books/1447303603s/2767052.jpg  
1  https://images.gr-assets.com/books/1474154022s/3.jpg        
2  https://images.gr-assets.com/books/1361039443s/41865.jpg    
3  https://images.gr-assets.com/books/1361975680s/2657.jpg     
4  https://images.gr-assets.com/books/1490528560s/4671.jpg

# Data pre-processing

In [65]:
# get unique books with title
books_sub = df[["book_id","title"]].copy()

In [66]:
books_sub.head()

book_id                                                     title
0  2767052  The Hunger Games (The Hunger Games, #1)                 
1  3        Harry Potter and the Sorcerer's Stone (Harry Potter, #1)
2  41865    Twilight (Twilight, #1)                                 
3  2657     To Kill a Mockingbird                                   
4  4671     The Great Gatsby

Vectorize Title

In [67]:
from sklearn.feature_extraction.text import CountVectorizer

In [87]:
# initialize vectorizer
#vect = CountVectorizer(analyzer='word',ngram_range=(1,2),stop_words='english', min_df = 0.001)
vect = CountVectorizer(analyzer='word',ngram_range=(1,3),stop_words='english', min_df = 0.001) #min_df - rare words , max_df - most used words
#ngram_range = (1,2) - if used more than 1(value), lot of features or noise

In [88]:
vect.fit(books_sub['title'])
title_matrix = vect.transform(books_sub['title'])

In [89]:
title_matrix.shape

(10000, 723)

In [90]:
# Find vocabulary
features = vect.get_feature_names()
features

['01',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '39',
 '39 clues',
 'academy',
 'adventures',
 'affair',
 'age',
 'agency',
 'alex',
 'alex cross',
 'alice',
 'allon',
 'amber',
 'america',
 'american',
 'ancient',
 'angel',
 'angels',
 'anita',
 'anita blake',
 'anita blake vampire',
 'anne',
 'apprentice',
 'armand',
 'armand gamache',
 'art',
 'ashes',
 'assassin',
 'autobiography',
 'away',
 'baby',
 'bad',
 'bastard',
 'batman',
 'battle',
 'beach',
 'bear',
 'beautiful',
 'beauty',
 'best',
 'big',
 'black',
 'black dagger',
 'black dagger brotherhood',
 'blake',
 'blake vampire',
 'blake vampire hunter',
 'blood',
 'blue',
 'body',
 'bolitar',
 'bone',
 'bones',
 'book',
 'book fallen',
 'books',
 'born',
 'bosch',
 'bosch universe',
 'box',
 'boxed',
 'boxed set',
 'boy',
 'boys',
 'brain',
 'breaking',
 'breed',
 'brennan',
 'bride',
 'bridge',
 'bright',
 'broken',
 'brotherhood',
 'brothers',
 'burning',
 'business',


In [15]:
len(features)

261

In [16]:
# What happens when we change the value of min_df value? What is this argument controlling?

In [17]:
# confirm count of features in the corpus
word_count = [books_sub["title"].str.contains("\\b"+x+"\\b", case=False).sum() for x in features]
word_count

[23,
 69,
 57,
 52,
 44,
 35,
 29,
 21,
 21,
 36,
 42,
 23,
 37,
 46,
 28,
 30,
 23,
 23,
 26,
 55,
 32,
 24,
 35,
 24,
 21,
 40,
 95,
 23,
 0,
 60,
 56,
 24,
 33,
 28,
 122,
 24,
 20,
 26,
 26,
 44,
 22,
 28,
 25,
 20,
 23,
 22,
 49,
 166,
 25,
 66,
 51,
 49,
 20,
 33,
 36,
 20,
 138,
 1,
 26,
 37,
 43,
 21,
 28,
 45,
 28,
 80,
 114,
 0,
 24,
 23,
 39,
 29,
 20,
 41,
 26,
 31,
 29,
 32,
 24,
 39,
 23,
 38,
 36,
 32,
 51,
 20,
 28,
 21,
 30,
 29,
 20,
 43,
 28,
 107,
 49,
 35,
 57,
 20,
 20,
 26,
 51,
 28,
 48,
 35,
 58,
 21,
 63,
 26,
 22,
 53,
 26,
 25,
 25,
 29,
 32,
 60,
 37,
 110,
 25,
 56,
 35,
 26,
 24,
 26,
 51,
 23,
 21,
 29,
 27,
 23,
 23,
 23,
 72,
 24,
 24,
 35,
 25,
 21,
 30,
 25,
 20,
 34,
 179,
 31,
 27,
 111,
 25,
 25,
 31,
 42,
 55,
 145,
 21,
 21,
 65,
 21,
 134,
 28,
 35,
 23,
 41,
 24,
 23,
 24,
 43,
 30,
 47,
 77,
 146,
 27,
 25,
 25,
 29,
 26,
 32,
 29,
 26,
 24,
 42,
 24,
 22,
 0,
 33,
 34,
 44,
 23,
 25,
 72,
 35,
 25,
 33,
 21,
 20,
 80,
 23,
 30,
 23,
 39,
 27

# Find Similarity Between Items

In [91]:
from sklearn.metrics.pairwise import cosine_similarity

In [92]:
cosine_sim_titles = cosine_similarity(title_matrix, title_matrix)

In [93]:
cosine_sim_titles.shape

(10000, 10000)

In [58]:
cosine_sim_titles

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [61]:
cosine_sim_titles[bookId].shape

(10000,)

In [94]:
bookId = 1854
print(books_sub.loc[bookId,'title'])
print(np.sort(cosine_sim_titles[bookId])[:-10:-1])
print(cosine_sim_titles[bookId].argsort()[:-10:-1])
books_sub.loc[cosine_sim_titles[bookId].argsort()[:-10:-1],['title']]

The Seven Spiritual Laws of Success: A Practical Guide to the Fulfillment of Your Dreams
[1.         0.70710678 0.5        0.5        0.5        0.5
 0.5        0.5        0.5       ]
[1854 4403 5599 7522 4363 4102 7401 6783 6061]


title
1854  The Seven Spiritual Laws of Success: A Practical Guide to the Fulfillment of Your Dreams                      
4403  The 7 Habits of Highly Effective Teens: The Ultimate Teenage Success Guide                                    
5599  The Hollow (Sign of Seven, #2)                                                                                
7522  Hogwarts: An Incomplete and Unreliable Guide (Pottermore Presents, #3)                                        
4363  The Success Principles: How to Get from Where You Are to Where You Want to Be                                 
4102  Einstein's Dreams                                                                                             
7401  The Happiness Advantage: The Seven Principles of Positive Psychology That Fuel Success and Performance at Work
6783  Ina May's Guide to Childbirth                                                                                 
6061  Waking Up: A Guide to Spirituality Without Religion

In [59]:
bookId = 1854
print(books_sub.loc[bookId,'title'])
print(np.sort(cosine_sim_titles[bookId])[:-10:-1])
print(cosine_sim_titles[bookId].argsort()[:-10:-1])
books_sub.loc[cosine_sim_titles[bookId].argsort()[:-10:-1],['title']]

The Seven Spiritual Laws of Success: A Practical Guide to the Fulfillment of Your Dreams
[1.         0.81649658 0.57735027 0.57735027 0.57735027 0.57735027
 0.57735027 0.57735027 0.57735027]
[1854 9972 1188 9349 3008 1751 5136 8851 1331]


title
1854  The Seven Spiritual Laws of Success: A Practical Guide to the Fulfillment of Your Dreams                        
9972  The Seven Principles for Making Marriage Work: A Practical Guide from the Country's Foremost Relationship Expert
1188  The Monk Who Sold His Ferrari: A Fable About Fulfilling Your Dreams  Reaching Your Destiny                      
9349  The Traveler's Gift: Seven Decisions that Determine Personal Success                                            
3008  Rich Dad's Cashflow Quadrant: Rich Dad's Guide to Financial Freedom                                             
1751  Animal Dreams                                                                                                   
5136  Sweet Dreams (Colorado Mountain, #2)                                                                            
8851  Wildest Dreams (Fantasyland, #1)                                                                                
1331  Mostly Harmless (Hitchhiker's Guide to the Galaxy, #5)

In [41]:
# get books similiar to a given title
title_id = 3
books_sub['title'].iloc[title_id]

'To Kill a Mockingbird'

In [42]:
np.argsort(cosine_sim_titles[1,])

array([   0, 6656, 6657, ..., 7017, 9282,    1])

In [43]:
top_n_idx = np.flip(np.argsort(cosine_sim_titles[title_id,]),axis=0)[0:10]
top_n_sim_values = cosine_sim_titles[title_id, top_n_idx]
top_n_sim_values

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
# find top n with values > 0
top_n_idx = top_n_idx[top_n_sim_values > 0]

In [45]:
# Matching books
books_sub['title'].iloc[top_n_idx]

Series([], Name: title, dtype: object)

# Consider the book - "To Kill a Mockingbird" (location_id - 3). 
What are the most similiar books? Why does "First to Kill", "Kill me if you can" etc all have same ratings?

In [40]:
## get books similiar to a given title
title_id = 1 # make this 3
books_sub['title'].iloc[title_id]

"Harry Potter and the Sorcerer's Stone (Harry Potter, #1)"

# Find out what features have been considered by the vectorizer for a given title?

In [43]:
np.where(np.squeeze(title_matrix[9247,].toarray()) > 0)

(array([], dtype=int64),)

In [59]:
features[245]

'war'

In [62]:
# To find out non-zero values from the Count vectorizer matrix
title_id = 7017
print(books_sub.loc[title_id,'title'])
print(title_matrix[title_id,])
feature_array = np.squeeze(title_matrix[title_id,].toarray())
idx = np.where(feature_array > 0)
idx[0]

The Magical Worlds of Harry Potter: A Treasury of Myths, Legends, and Fascinating Facts
  (0, 106)	1
  (0, 108)	1
  (0, 177)	1


array([106, 108, 177])

In [47]:
[features[x] for x in idx[0]]

['harry', 'harry potter', 'potter']

In [48]:
# lets wrap the above code in a function
def return_sim_books(title_id, title_matrix, vectorizer, top_n = 10):
    
    # generate sim matrix
    sim_matrix = cosine_similarity(title_matrix, title_matrix)
    features = vectorizer.get_feature_names()



    top_n_idx = np.flip(np.argsort(sim_matrix[title_id,]),axis=0)[0:top_n]
    top_n_sim_values = sim_matrix[title_id, top_n_idx]
    
    # find top n with values > 0
    top_n_idx = top_n_idx[top_n_sim_values > 0]
    scores = top_n_sim_values[top_n_sim_values > 0]
    
    
    # find features from the vectorized matrix
    sim_books_idx = books_sub['title'].iloc[top_n_idx].index
    words = []
    for book_idx in sim_books_idx:
        try:
            feature_array = np.squeeze(title_matrix[book_idx,].toarray())
        except:
            feature_array = np.squeeze(title_matrix[book_idx,])
        idx = np.where(feature_array > 0)
        words.append([" , ".join([features[i] for i in idx[0]])])
        
    # collate results
    res = pd.DataFrame({"book_title" : books_sub['title'].iloc[title_id],
           "sim_books": books_sub['title'].iloc[top_n_idx].values,"words":words,
           "scores":scores}, columns = ["book_title","sim_books","scores","words"])
    
    
    return res


In [49]:
vect = CountVectorizer(analyzer='word',ngram_range=(1,2),stop_words='english', min_df = 0.001)
vect.fit(books_sub['title'])
title_matrix = vect.transform(books_sub['title'])
return_sim_books(1854,title_matrix,vect,top_n=20)

book_title  \
0   The Seven Spiritual Laws of Success: A Practic...   
1   The Seven Spiritual Laws of Success: A Practic...   
2   The Seven Spiritual Laws of Success: A Practic...   
3   The Seven Spiritual Laws of Success: A Practic...   
4   The Seven Spiritual Laws of Success: A Practic...   
5   The Seven Spiritual Laws of Success: A Practic...   
6   The Seven Spiritual Laws of Success: A Practic...   
7   The Seven Spiritual Laws of Success: A Practic...   
8   The Seven Spiritual Laws of Success: A Practic...   
9   The Seven Spiritual Laws of Success: A Practic...   
10  The Seven Spiritual Laws of Success: A Practic...   
11  The Seven Spiritual Laws of Success: A Practic...   
12  The Seven Spiritual Laws of Success: A Practic...   
13  The Seven Spiritual Laws of Success: A Practic...   
14  The Seven Spiritual Laws of Success: A Practic...   
15  The Seven Spiritual Laws of Success: A Practic...   
16  The Seven Spiritual Laws of Success: A Practic...   
17  The Seven Spiritual Laws of Success: A Practic...   
18  The Seven Spiritual Laws of Success: A Practic...   
19  The Seven Spiritual Laws of Success: A Practic...   

                                            sim_books    scores  \
0   The Seven Spiritual Laws of Success: A Practic...  1.000000   
1   The 7 Habits of Highly Effective Teens: The Ul...  0.707107   
2                      The Hollow (Sign of Seven, #2)  0.500000   
3   Hogwarts: An Incomplete and Unreliable Guide (...  0.500000   
4   The Success Principles: How to Get from Where ...  0.500000   
5                                   Einstein's Dreams  0.500000   
6   The Happiness Advantage: The Seven Principles ...  0.500000   
7                       Ina May's Guide to Childbirth  0.500000   
8   Waking Up: A Guide to Spirituality Without Rel...  0.500000   
9     Preach My Gospel: A Guide To Missionary Service  0.500000   
10             Succubus Dreams (Georgina Kincaid, #3)  0.500000   
11  The Hitchhiker's Guide to the Galaxy (Hitchhik...  0.500000   
12                         The Seven-Percent Solution  0.500000   
13  The Traveler's Gift: Seven Decisions that Dete...  0.500000   
14  Give and Take: A Revolutionary Approach to Suc...  0.500000   
15  Mostly Harmless (Hitchhiker's Guide to the Gal...  0.500000   
16                   Wildest Dreams (Fantasyland, #1)  0.500000   
17                                      Animal Dreams  0.500000   
18  How I Raised Myself from Failure to Success in...  0.500000   
19                        Vain (The Seven Deadly, #1)  0.500000   

                                   words  
0     [dreams , guide , seven , success]  
1                      [guide , success]  
2                                [seven]  
3                                [guide]  
4                              [success]  
5                               [dreams]  
6   [happiness , seven , success , work]  
7                                [guide]  
8                                [guide]  
9                                [guide]  
10                              [dreams]  
11                               [guide]  
12                               [seven]  
13   [gift , personal , seven , success]  
14                             [success]  
15                               [guide]  
16                              [dreams]  
17                              [dreams]  
18                             [success]  
19                               [seven]

In [ ]:
Hang him not, leave him

In [ ]:
Hang him, not leave him